### ISSUE TITLE
Program crashes on invalid argument count

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2021sp-420-JINXS#112]
**As a** User
**When** I type "add method" without any required arguments
**Then** the program should present an error message **and not crash** 😄

```
$ add method
Too few Arguments for addMethod command
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.jinxs.umleditor.UMLInterface.commandInterface(UMLInterface.java:93)
	at org.jinxs.umleditor.UMLInterface.main(UMLInterface.java:365)
```

**Comment by natshenk** [comment]
Noted during integration testing, but found too late to act upon :(
